INSERT INTO AT_FILE(IDENTIFIER,URL,NAME,EXTENSION,MIME,SIZE,AUDIT_IDENTIFIER,AUDIT_FUNCTIONALITY,AUDIT_ACTION,AUDIT_ACTOR,AUDIT_DATE) VALUES ('3','http://localhost:10000/f02.txt','name01','ext01','text/plain',100,'a','f','w','a', DATE '2000-1-1');
INSERT INTO AT_FILE(IDENTIFIER,URL,NAME,EXTENSION,MIME,SIZE,AUDIT_IDENTIFIER,AUDIT_FUNCTIONALITY,AUDIT_ACTION,AUDIT_ACTOR,AUDIT_DATE) VALUES ('2','http://localhost:10000/f03.txt','name03','ext03','text/plain',300,'a','f','w','a', DATE '2000-1-1');
INSERT INTO AT_FILE(IDENTIFIER,URL,NAME,EXTENSION,MIME,SIZE,AUDIT_IDENTIFIER,AUDIT_FUNCTIONALITY,AUDIT_ACTION,AUDIT_ACTOR,AUDIT_DATE) VALUES ('1','http://localhost:10000/f01.txt','name02','ext02','text/html',200,'a','f','w','a', DATE '2000-1-1');

INSERT INTO AT_FILE_BYTES(IDENTIFIER,BYTES,AUDIT_IDENTIFIER,AUDIT_FUNCTIONALITY,AUDIT_ACTION,AUDIT_ACTOR,AUDIT_DATE) VALUES ('2','68656c6c6f20776f726c6421','a','f','w','a', DATE '2000-1-1');
--INSERT INTO AT_FILE(IDENTIFIER,URI,NAME,EXTENSION,MIME,SIZE,SHA1) VALUES ('4','d4/d4_f1.txt','name04','ext04','mime04',100,'sha04');

INSERT INTO AT_FILE_TEXT(IDENTIFIER,TEXT,AUDIT_IDENTIFIER,AUDIT_FUNCTIONALITY,AUDIT_ACTION,AUDIT_ACTOR,AUDIT_DATE) VALUES ('2','You are lord','a','f','w','a', DATE '2000-1-1');